### ISSUE TITLE
Failed to load external module babel-register

### ISSUE THREAD

**Issue by idhard** [AngularClass/NG6-starter#124] opened 2016-03-25 10:11 UTC
After following the steps to install the starter im getting the following errors when running 

` gulp serve `

[12:05:45] Failed to load external module babel-register
[12:05:45] Requiring external module babel-core/register
[12:05:46] Using gulpfile ~/Sites/cnd-gemo/gulpfile.babel.js
[12:05:46] Starting 'serve'...
[12:05:46] Finished 'serve' after 238 ms
[BS] Access URLs:
 ------------------------------------
       Local: http://localhost:3000
    External: http://192.168.2.6:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.2.6:3001
 ------------------------------------
[BS] Serving files from: client
webpack built 2ac0348a475b55f7ff15 in 3023ms
Hash: 2ac0348a475b55f7ff15
Version: webpack 1.12.14
Time: 3023ms
               Asset     Size  Chunks             Chunk Names
       app.bundle.js  20.8 kB       0  [emitted]  app
    vendor.bundle.js  1.46 MB       1  [emitted]  vendor
   app.bundle.js.map  25.4 kB       0  [emitted]  app
vendor.bundle.js.map  1.69 MB       1  [emitted]  vendor
          index.html  1.27 kB          [emitted]  
webpack: bundle is now VALID.

the build is correctly done but when i try to access to the website im getting this error : 

> TypeError: Cannot read property 'indexOf' of undefined
>     at getFilenameFromUrl (/Users/odifisIH/Sites/cnd-gemo/node_modules/webpack-dev-middleware/middleware.js:129:9)
>     at webpackDevMiddleware (/Users/odifisIH/Sites/cnd-gemo/node_modules/webpack-dev-middleware/middleware.js:174:18)
>     at call (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:239:7)
>     at next (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:183:5)
>     at /Users/odifisIH/Sites/cnd-gemo/node_modules/connect-history-api-fallback/lib/index.js:72:5
>     at call (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:239:7)
>     at next (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:183:5)
>     at respModifierMiddleware (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/resp-modifier/index.js:80:9)
>     at call (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:239:7)
>     at next (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:183:5)
>     at next (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:161:14)
>     at next (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:161:14)
>     at utils.handleOldIE (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/lib/server/utils.js:95:16)
>     at call (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:239:7)
>     at next (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:183:5)
>     at next (/Users/odifisIH/Sites/cnd-gemo/node_modules/browser-sync/node_modules/connect/index.js:161:14)

some more relevant information , the ticket could be related to #117 : 

here my environment configuration : 

gulp -v
[17:28:12] CLI version 3.9.1
[17:28:12] Local version 3.9.1

node -v 
v5.9.1

running on mac ox x 10.11.3 

thanks

**Comment by fesor** [comment] 2016-03-26 11:01
Thanks for reporting! Update `webpack-dev-middleware` to master or downgrade to `1.5.1`. Broken commit already reverted, new version should be published asap. See more details in related issue: https://github.com/webpack/webpack-dev-middleware/issues/82

Also closing this since it duplicate of https://github.com/AngularClass/NG6-starter/issues/117.

**Closed by fesor** 2016-03-26 11:01 UTC
