### ISSUE TITLE
Error on gulp webpack

### ISSUE THREAD

**Issue by ghernandez81** [AngularClass/NG6-starter#113] opened 2016-03-04 16:20 UTC
i have this error running `gulp webpack` :

```
sui-seed-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
```

**Comment by samithaf** [comment] 2016-03-31 09:37
Which env you are in? I have setup the project in osx without any issues. Few things that you can check, Node version ( I am using 4.2 ). Also you can try to update the babel version to 6.X and see if it solves the issue

**Comment by fesor** [comment] 2016-11-23 19:55
I can't reproduce this issue. Since there is no any activity, I probably will close this. @ghernandez81 Please feel free to comment if you think that it should be reopened.

**Closed by fesor** 2016-11-23 19:55 UTC

**Comment by ghernandez81** [comment] 2016-11-23 21:13
go ahead close it, it work for me now
